language: python
# available Python versions:
# https://docs.travis-ci.com/user/languages/python/#Development-releases-support
python:
    - "3.5"
    - "3.6"
install:
    - make install
script:
    - make test
